package com.github.skjolber.bank.example.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T11:58:31.982+05:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://example.bank.skjolber.github.com/v1", name = "BankCustomerServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankCustomerServicePortType {

    @WebMethod
    @WebResult(name = "getAccountsResponse", targetNamespace = "http://example.bank.skjolber.github.com/v1", partName = "parameters")
    public GetAccountsResponse getAccounts(

        @WebParam(partName = "parameters", name = "getAccountsRequest", targetNamespace = "http://example.bank.skjolber.github.com/v1")
        GetAccountsRequest parameters
    ) throws CustomerException_Exception, BankException_Exception;
}
