
package com.github.skjolber.bank.example.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T11:58:31.944+05:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "fault", targetNamespace = "http://example.bank.skjolber.github.com/v1")
public class CustomerException_Exception extends Exception {

    private com.github.skjolber.bank.example.v1.CustomerException fault;

    public CustomerException_Exception() {
        super();
    }

    public CustomerException_Exception(String message) {
        super(message);
    }

    public CustomerException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CustomerException_Exception(String message, com.github.skjolber.bank.example.v1.CustomerException fault) {
        super(message);
        this.fault = fault;
    }

    public CustomerException_Exception(String message, com.github.skjolber.bank.example.v1.CustomerException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.github.skjolber.bank.example.v1.CustomerException getFaultInfo() {
        return this.fault;
    }
}
