package com.github.skjolber.bank.example.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T11:58:32.002+05:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "BankCustomerService",
                  wsdlLocation = "file:src/main/resources/sample.wsdl",
                  targetNamespace = "http://example.bank.skjolber.github.com/v1")
public class BankCustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.bank.skjolber.github.com/v1", "BankCustomerService");
    public final static QName BankCustomerServicePort = new QName("http://example.bank.skjolber.github.com/v1", "BankCustomerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/sample.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankCustomerService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/sample.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankCustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankCustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankCustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BankCustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankCustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankCustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BankCustomerServicePortType
     */
    @WebEndpoint(name = "BankCustomerServicePort")
    public BankCustomerServicePortType getBankCustomerServicePort() {
        return super.getPort(BankCustomerServicePort, BankCustomerServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankCustomerServicePortType
     */
    @WebEndpoint(name = "BankCustomerServicePort")
    public BankCustomerServicePortType getBankCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(BankCustomerServicePort, BankCustomerServicePortType.class, features);
    }

}
