
package com.github.skjolber.bank.example.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-04T11:58:31.974+05:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "bankException", targetNamespace = "http://example.bank.skjolber.github.com/v1")
public class BankException_Exception extends Exception {

    private com.github.skjolber.bank.example.v1.BankException bankException;

    public BankException_Exception() {
        super();
    }

    public BankException_Exception(String message) {
        super(message);
    }

    public BankException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public BankException_Exception(String message, com.github.skjolber.bank.example.v1.BankException bankException) {
        super(message);
        this.bankException = bankException;
    }

    public BankException_Exception(String message, com.github.skjolber.bank.example.v1.BankException bankException, java.lang.Throwable cause) {
        super(message, cause);
        this.bankException = bankException;
    }

    public com.github.skjolber.bank.example.v1.BankException getFaultInfo() {
        return this.bankException;
    }
}
